Docker 4
Otus-DevOps-2021-11/JakUi_microservices pull request #4
Opened 2022-02-11 18:04 UTC by JakUi

# Выполнено ДЗ №18

 - [X] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Все задания, кроме задания со *

## Как запустить проект:
 - В каталоге `src` выполнить команду `docker-compose up -d`

## Как проверить работоспособность:
 - Перейти по ссылке http://51.250.9.81:9292/
## PR checklist
 - [X] Выставил label с номером домашнего задания
 - [X] Выставил label с темой домашнего задания

2022-02-11 18:05 UTC, JakUi commented
12.02.22 покупаю/купил игровой комп - нужен аппрув (могу не вернуться к ДЗ в выходные))

2022-02-12 12:06 UTC, mrgreyves requested changes
Здравствуйте!)
Вдруг игровой ПеКа еще не приехал =)
Нужно поправить переменные
  expected: ""
          got: "The USERNAME variable is not set. Defaulting to a blank string.\n"
Кажется что  быстро =)

2022-02-12 15:09 UTC, JakUi commented
Про тесты я и забыл. Сейчас поправлю, спасибо)

2022-02-13 16:01 UTC, mrgreyves approved these changes
Здравствуйте!)
Проверил ваше дз
Все задания выполнены корректно, апрув =)

2022-02-14 07:23 UTC, merged